name: next_available_name
description: Get next available name.
version: 1.1.0
repository: https://github.com/flutter-cavalry/next_available_name

environment:
  sdk: ">=2.18.6 <4.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
